[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# Unite
# 2016/08/05
[[plugins]]
repo = 'Shougo/unite.vim'
hook_add = '''
nnoremap [unite]  <Nop>
nmap     <C-u>    [unite]

nnoremap <silent> <C-t><C-c>   :<C-u>UniteWithCurrentDir -buffer-name=files buffer file_mru bookmark file<CR>
nnoremap <silent> <C-t><C-t>   :<C-u>Unite buffer<CR>
nnoremap <silent> <C-t>t       :<C-u>Unite buffer<CR>

" The prefix key.
nnoremap    [Tag]   <Nop>
nmap    <C-t> [Tag]

" tc 新しいタブを一番右に作る
map <silent> [Tag]c :tablast <bar> tabnew<CR>
" tn 次のタブ
map <silent> [Tag]n :tabnext<CR>
nnoremap <silent> <C-j> :tabnext<CR>
" tp 前のタブ
map <silent> [Tag]p :tabprev<CR>
nnoremap <silent> <C-k> :tabprev<CR>
" tw タブを閉じる
map <silent> [Tag]w :bdelete<CR>
'''

[[plugins]]
repo = 'Shougo/neomru.vim'

# Jedi Python
# 2016/08/05
[[plugins]]
repo = 'davidhalter/jedi-vim'
hook_add = '''
" jediにvimの設定を任せると'completeopt+=preview'するので
" 自動設定機能をOFFにし手動で設定を行う
let g:jedi#auto_vim_configuration = 0
" 補完の最初の項目が選択された状態だと使いにくいためオフにする
let g:jedi#popup_select_first = 0
" quickrunと被るため大文字に変更
let g:jedi#rename_command = '<Leader>R'
" gundoと被るため大文字に変更 (2013-06-24 10:00 追記）
let g:jedi#goto_command = '<Leader>G'
'''

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'scrooloose/syntastic'
hook_add = '''
" syntasticとflake8で文法チェックを行う
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_python_checkers = ["flake8"]
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
'''

[[plugins]]
repo = 'janko-m/vim-test'

[[plugins]]
repo = 'pangloss/vim-javascript'

# vim-go
# 2018/03/11
[[plugins]]
repo = 'fatih/vim-go'
hook_add = '''
let g:go_fmt_autosave = 1
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'
