# Required:
[[plugins]]
repo = 'Shougo/dein.vim'

# Airline
# 2016/08/05
[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
set laststatus=2
set showtabline=2 " 常にタブラインを表示
set t_Co=256
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#buffer_idx_mode = 1
let g:airline_theme='papercolor'
let g:airline_powerline_fonts = 1
"let g:Powerline_symbols = 'fancy'
'''
depends = ['vim-airline-themes']

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
